### ISSUE TITLE
Pattern matching for mapped values

### ISSUE THREAD

**Issue by revgum** [osulp/dspace2hydra#11]
“If DSpace description(without a qualifier) starts with ‘Graduation’, then extract the date and put it in a Date field for graduation for ETD types.” … So this is expressing pattern matching on a mapped value, if the pattern passed then it maps differently than if the pattern doesn’t match.

Somewhat related to #12 and #13 .. matches should allow for the `value_format` as well.

So something like this would allow for an array of patterns to be evaluated and mapped to a form_field.
```

description:
    qualifiers:
        default:
            form_field: default_work['additional_information'][]
            matches:
                -
                    pattern: '^Graduation\w+'
                    form_field: default_work['date']['graduated']
```
