### ISSUE TITLE
Format value configuration

### ISSUE THREAD

**Issue by revgum** [osulp/dspace2hydra#13]
Provide the ability to do some sort of formatting on the value that is being mapped. See #12 

So something like;
```

description:
    peerreview:
        qualifiers:
            default:
                form_field: default_work[additional_information]
                value_format: "description.peerreview : {value}"
```
