### ISSUE TITLE
add "academic_unit" configuration to all other configurations

### ISSUE THREAD

**Issue by revgum** [osulp/dspace2hydra#139]
```
academic_unit:
    field:
      name: academic_unit
      property: "%{work_type}.%{field_name}"
      type: Array
    method: Mapping::AcademicUnit.get_uris
    value_from_node_property: item_detail
```
