### ISSUE TITLE
Ignore mapping a field

### ISSUE THREAD

**Issue by revgum** [osulp/dspace2hydra#14]
Provide the means for explicitly ignoring the mapping of a field.

See #11 #12 #13 

```
some_element:
    ignore: true
    qualifiers:
        default:
...
```
