### ISSUE TITLE
degree name metadata handling

### ISSUE THREAD

**Issue by revgum** [osulp/dspace2hydra#20]
Provide the ability to split a value, and map an expected array of results..  See #12 

`Doctor of Philosophy (Ph. D.) in Geography` would be mapped to:

`default_work[degree_name][] = 'Doctor of Philosophy (Ph. D.)'`
and
`default_work[degree_field][] = 'Geography'`

So something like;
```

degree:
    name:
        qualifiers:
            default:
                form_field: default_work[additional_information]
                value_split_operations:
                    split_on: " in "
                    mapped_values:
                        - 
                            form_field: default_work[degree_name][]
                        -
                            form_field: default_work[degree_field][]
```
